Add new opt-in flag to specify the output_file_mode to produce more deterministic behavior across operating systems.
hashicorp/terraform-provider-archive pull request #90
Opened 2021-03-21 01:36 UTC by virgofx

This adds **new** functionality to address the deterministic behavior via an additional **opt-in parameter**. This is non-breaking with respect to existing functionality; however, should be helpful in that it will reduce the numerous issues resolving non-deterministic behavior for those that build cross platform by allowing them to set file output mode.

✔️ Tests included

Fixes via Workaround for:
- #34 
- #53 
- #58 
- #10 

Other References:
- #41 

Would love to get this reviewed and hopefully merged. 

/cc: @appilon @EamonHetherton @Supermathie @maxrothman @timwsuqld @nathanielks @karolkania @saveriomiroddi @xarses @sapher @quixand @olfway @bee-keeper

2021-03-21 01:36 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/terraform-provider-archive?pullRequest=90)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/terraform-provider-archive?pullRequest=90)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/terraform-provider-archive?pullRequest=90).</sub>

2021-03-21 08:44 UTC, saveriomiroddi commented
This may work for a significant part of the cases, but not all. #34 is a wider issue, which includes different O/S libraries producing different compressed streams.

Please not CC me, the maintainers are incompetent and I don't want to have anything to do with this project.

2021-03-21 18:33 UTC, virgofx commented
Definitely share your frustration with the lack of attention to this issue, which is why I spent a day to come up with a better opt-in approach to at least solve this without having to maintain a fork (which I did not want to do). I still think this issue would resolve the umask/permissions issues described in #34 by directly specifying the permissions. I don't see the changes here as breaking in anyway so I'm hoping the maintainers would at least compromise and include this work around.

2021-03-21 18:42 UTC, saveriomiroddi commented
> Definitely share your frustration with the lack of attention to this issue, which is why I spent a day to come up with a better opt-in approach to at least solve this without having to maintain a fork (which I did not want to do). I still think this issue would resolve the umask/permissions issues described in #34 by directly specifying the permissions. I don't see the changes here as breaking in anyway so I'm hoping the maintainers would at least compromise and include this work around.

Ah, I think I've been ambiguos - didn't meant to diminish this work :) I think like you, that any work that goes upstream, is definitely an improvement of the status quo! :smile: Good luck :grimacing:

2021-04-13 14:47 UTC, kmoe requested changes
Thank you for this PR, @virgofx. I believe this provides a reasonable way for most users to ensure deterministic zip creation across OSs.

I've added some acceptance tests in #92 to demonstrate the fix, using the fact that our CI builds run across Ubuntu, macOS, and Windows. Please cherry-pick 4246a0c and 4ddf87a (squashed together if you like) onto your branch. We now check the exact value of the hashes, which I think is fine, as we want to know if the bytes of the zip change for any other reason anyway.

I'm going to request that users experiencing #34 test whether the `archive_file_mode` workaround enabled by this PR works for them.

2021-04-13 14:47 UTC, kmoe commented on internal/provider/zip_archiver_test.go
> +	r, err := zip.OpenReader(zipfilepath)
Please add `t.Helper()` to `ensureFileMode` (and to `ensureContent` and `ensureContents` while you're at it, if you don't mind).

2021-04-13 16:38 UTC, virgofx commented
Updated with acceptance tests and `t.Helper()` on helper functions.

2021-05-04 10:11 UTC, kmoe approved these changes

2021-05-04 10:12 UTC, kmoe commented
Thanks, @virgofx - looks good. This will be released today in v2.2.0.

2021-05-04 10:12 UTC, merged

2021-05-05 05:04 UTC, virgofx commented
Thanks @kmoe. Maybe we should do some spring cleanup on the referenced issues making a note to this PR and then close accordingly. I feel this provider is fairly stable and it would allow more attention to other open PRs.